# Pipedriveのdeal.owner_idをSlackユーザーIDに対応付けます
23039236: U08AKQR58UQ # Shoichi Suyama
18237788: U012V9F268Y # Hiroki Ukeda
23263603: U08H0K8GAUU # Honoka Hayata
23383767: U08GQL3U362 # Reo Takamatsu
23263592: U08FCJ3CL5V # Taiga Watanabe
24167968: U03HP6CM1FB # Kohei Tokida

